"""Initial migration

Revision ID: 78af732a4729
Revises: 
Create Date: 2024-10-29 22:29:21.988371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78af732a4729'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autori_id'), 'autori', ['id'], unique=False)
    op.create_index(op.f('ix_autori_ime'), 'autori', ['ime'], unique=False)
    op.create_table('zanrovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zanrovi_id'), 'zanrovi', ['id'], unique=False)
    op.create_index(op.f('ix_zanrovi_ime'), 'zanrovi', ['ime'], unique=False)
    op.create_table('clanovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(), nullable=True),
    sa.Column('omiljeni_zanr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['omiljeni_zanr_id'], ['zanrovi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clanovi_id'), 'clanovi', ['id'], unique=False)
    op.create_index(op.f('ix_clanovi_ime'), 'clanovi', ['ime'], unique=False)
    op.create_table('knjige',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naslov', sa.String(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knjige_id'), 'knjige', ['id'], unique=False)
    op.create_index(op.f('ix_knjige_naslov'), 'knjige', ['naslov'], unique=False)
    op.create_table('citanje_knjige',
    sa.Column('knjiga_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.ForeignKeyConstraint(['knjiga_id'], ['knjige.id'], ),
    sa.PrimaryKeyConstraint('knjiga_id', 'clan_id')
    )
    op.create_table('knjiga_zanr',
    sa.Column('knjiga_id', sa.Integer(), nullable=False),
    sa.Column('zanr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knjiga_id'], ['knjige.id'], ),
    sa.ForeignKeyConstraint(['zanr_id'], ['zanrovi.id'], ),
    sa.PrimaryKeyConstraint('knjiga_id', 'zanr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knjiga_zanr')
    op.drop_table('citanje_knjige')
    op.drop_index(op.f('ix_knjige_naslov'), table_name='knjige')
    op.drop_index(op.f('ix_knjige_id'), table_name='knjige')
    op.drop_table('knjige')
    op.drop_index(op.f('ix_clanovi_ime'), table_name='clanovi')
    op.drop_index(op.f('ix_clanovi_id'), table_name='clanovi')
    op.drop_table('clanovi')
    op.drop_index(op.f('ix_zanrovi_ime'), table_name='zanrovi')
    op.drop_index(op.f('ix_zanrovi_id'), table_name='zanrovi')
    op.drop_table('zanrovi')
    op.drop_index(op.f('ix_autori_ime'), table_name='autori')
    op.drop_index(op.f('ix_autori_id'), table_name='autori')
    op.drop_table('autori')
    # ### end Alembic commands ###
